services:
  localstack:
    image: localstack/localstack:3.7.0
    ports:
      - "4566:4566" # main
      - "8000:8000" # dynamodb
    environment:
      - SERVICES=s3,lambda,logs,dynamodb
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - "./docker/volumes/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
